=== OriShitrit7/guess-market/samples/GM-EX2-Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="initial-cash" action="xs:int"/>
	<xs:element name="id" action="xs:int"/>
	<xs:element name="event">
		<xs:complexType>
			<xs:attribute name="id" action="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="description" action="xs:string"/>
	<xs:element name="commission">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:int">
					<xs:attribute name="action" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="on-close"/>
								<xs:enumeration value="on-purchase"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="b" action="xs:int"/>
	<xs:element name="Guess-Market">
		<xs:complexType>
			<xs:all>
				<xs:element ref="GM-events"/>
				<xs:element ref="GM-users"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-users">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GM-user" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-user">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="initial-cash"/>
				<xs:element ref="GM-market-maker" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" action="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-order-book">
		<xs:complexType>
			<xs:attribute name="initial" action="xs:int" use="required"/>
			<xs:attribute name="d" action="xs:int" use="required"/>
			<xs:attribute name="allow-mint" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="false"/>
						<xs:enumeration value="true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-options">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GM-option" maxOccurs="2"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-option" action="xs:string"/>
	<xs:element name="GM-method">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="GM-LMSR"/>
				<xs:element ref="GM-order-book"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-market-maker">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="event" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-events">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GM-event" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-event">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="description"/>
				<xs:element ref="commission"/>
				<xs:element ref="GM-options"/>
				<xs:element ref="GM-method"/>
			</xs:sequence>
			<xs:attribute name="name" action="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-LMSR">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="b"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== OriShitrit7/guess-market/samples/multiple.xml
<?xml version="1.0" encoding="UTF-8"?>
<Guess-Market xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GM-EX2-Schema.xsd">
	<GM-events>
		<GM-event name="Mujtaba is Dead">
			<id>1</id>
			<description>This event gambles if Mujtaba is a live or not. it will be determined if he will be shown in public until 31.8.26</description>
			<commission type="on-purchase">5</commission>
			<GM-options>
				<GM-option>Hell Yea !</GM-option>
				<GM-option>No way !</GM-option>
			</GM-options>
			<GM-method>
				<GM-LMSR>
					<b>100</b>
				</GM-LMSR>
			</GM-method>
		</GM-event>
		<GM-event name="World Cap Winner">
			<id>2</id>
			<description>Who do you think will win the world cap ?</description>
			<commission type="on-close">15</commission>
			<GM-options>
				<GM-option>Argentina</GM-option>
				<GM-option>Spain</GM-option>
			</GM-options>
			<GM-method>
				<GM-order-book allow-mint="true" initial="100" d="1"/>
			</GM-method>
		</GM-event>
		<GM-event name="Earth Quake on Dead Sea">
			<id>3</id>
			<description>Will there be an earth quake on the dead sea until the December 31th 2026</description>
			<commission type="on-purchase">50</commission>
			<GM-options>
				<GM-option>Yes</GM-option>
				<GM-option>No</GM-option>
			</GM-options>
			<GM-method>
				<GM-order-book allow-mint="false" initial="1000" d="1"/>
			</GM-method>
		</GM-event>
		<GM-event name="Will it rain tomorrow ?">
			<id>4</id>
			<description>Will there be 30 mm of rain tomorrow at Alenbi 283 st by 12:00 PM ?</description>
			<commission type="on-close">10</commission>
			<GM-options>
				<GM-option>Yes</GM-option>
				<GM-option>No</GM-option>
			</GM-options>
			<GM-method>
				<GM-LMSR>
					<b>200</b>
				</GM-LMSR>
			</GM-method>
		</GM-event>
	</GM-events>
	<GM-users>
		<GM-user name="Avrum">
			<initial-cash>1000</initial-cash>
			<GM-market-maker>
				<event id="2"/>
			</GM-market-maker>
		</GM-user>
		<GM-user name="Tikva">
			<initial-cash>10000</initial-cash>
			<GM-market-maker>
				<event id="1"/>
				<event id="4"/>
				<event id="3"/>
			</GM-market-maker>
		</GM-user>
		<GM-user name="Menash">
			<initial-cash>100</initial-cash>
		</GM-user>
	</GM-users>
</Guess-Market>

=== OriShitrit7/guess-market/samples/small.xml
<?xml version="1.0" encoding="UTF-8"?>
<Guess-Market  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GM-EX2-Schema.xsd">
	<GM-events>
		<GM-event name="Mujtaba is Dead">
			<id>1</id>
			<description>This event gambles if Mujtaba is a live or not. it will be determined if he will be shown in public until 31.8.26</description>
			<commission action="on-purchase">5</commission>
			<GM-options>
				<GM-option>Hell Yea !</GM-option>
				<GM-option>No way !</GM-option>
			</GM-options>
			<GM-method>
				<GM-LMSR>
					<b>100</b>
				</GM-LMSR>
			</GM-method>
		</GM-event>
		<GM-event name="World Cap Winner">
			<id>2</id>
			<description>Who do you think will win the world cap ?</description>
			<commission action="on-close">15</commission>
			<GM-options>
				<GM-option>Argentina</GM-option>
				<GM-option>Spain</GM-option>
			</GM-options>
			<GM-method>
				<GM-order-book allow-mint="true" initial="100" d="1"/>
			</GM-method>
		</GM-event>
	</GM-events>
	<GM-users>
		<GM-user name="Avrum">
			<initial-cash>1000</initial-cash>
			<GM-market-maker>
				<event id="2"/>
			</GM-market-maker>
		</GM-user>
		<GM-user name="Tikva">
			<initial-cash>10000</initial-cash>
			<GM-market-maker>
				<event id="1"/>
			</GM-market-maker>
		</GM-user>
		<GM-user name="Menash">
			<initial-cash>100</initial-cash>
		</GM-user>
	</GM-users>
</Guess-Market>
